/*
LocalOCR Sync — generated by esbuild; edit the TypeScript sources in src/ instead.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LocalOcrSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/format.ts
var MARKER_START = "<!-- localocr:start -->";
var MARKER_END = "<!-- localocr:end -->";
var UNCATEGORIZED = "\u672A\u5206\u985E";
var UNTITLED = "\u672A\u547D\u540D";
var MAX_TITLE_LENGTH = 60;
var TITLE_KEYS = ["title", "store", "name", "company"];
var MANAGED_KEYS = [
  "localocr_id",
  "created",
  "updated",
  "template",
  "template_name",
  "source",
  "confidence",
  "classifier",
  "tags"
];
function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function collapseWhitespace(value) {
  return value.replace(/\s+/g, " ").trim();
}
function deriveTitle(scan) {
  if (isPlainObject(scan.data)) {
    for (const key of TITLE_KEYS) {
      const value = scan.data[key];
      if (typeof value === "string" || typeof value === "number") {
        const title = collapseWhitespace(String(value));
        if (title) return title;
      }
    }
  }
  if (typeof scan.text === "string") {
    for (const line of scan.text.split(/\r?\n/)) {
      const title = collapseWhitespace(line);
      if (title) return title;
    }
  }
  return UNTITLED;
}
var WINDOWS_RESERVED = /^(con|prn|aux|nul|com[0-9]|lpt[0-9])$/i;
function sanitizeFileName(value, max = MAX_TITLE_LENGTH) {
  let name = value.replace(/[\u0000-\u001f\u007f]/g, " ").replace(/[\\/:*?"<>|#^[\]]/g, "");
  name = collapseWhitespace(name);
  const chars = Array.from(name);
  if (chars.length > max) name = chars.slice(0, max).join("");
  name = name.replace(/^[.\s]+/, "").replace(/[.\s]+$/, "");
  if (WINDOWS_RESERVED.test(name)) name = `${name}_`;
  return name;
}
function pad2(n) {
  return n < 10 ? `0${n}` : String(n);
}
function parseDate(...candidates) {
  for (const candidate of candidates) {
    if (typeof candidate !== "string") continue;
    const date = new Date(candidate);
    if (!Number.isNaN(date.getTime())) return date;
  }
  return /* @__PURE__ */ new Date();
}
function formatNoteTimestamp(iso, fallback) {
  const d = parseDate(iso, fallback);
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())} ${pad2(d.getHours())}${pad2(d.getMinutes())}`;
}
function formatDateTime(iso) {
  const d = parseDate(iso);
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())} ${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}
function formatClock(date) {
  return `${pad2(date.getHours())}:${pad2(date.getMinutes())}`;
}
function normalizeFolder(folder) {
  return folder.replace(/\\/g, "/").split("/").map((part) => part.trim()).filter((part) => part.length > 0 && part !== ".").join("/");
}
function joinPath(...parts) {
  return parts.filter((part) => part.length > 0).join("/");
}
function resolveTemplateName(templateId, templates) {
  if (!templateId) return null;
  const name = templates.get(templateId);
  return name && name.trim() ? name.trim() : templateId;
}
function buildNotePath(scan, opts) {
  var _a;
  const folder = normalizeFolder(opts.folder);
  const sub = opts.subfolderPerTemplate ? sanitizeFileName((_a = opts.templateName) != null ? _a : "") || UNCATEGORIZED : "";
  const title = sanitizeFileName(deriveTitle(scan)) || UNTITLED;
  const file = `${formatNoteTimestamp(scan.createdAt, scan.updatedAt)} ${title}.md`;
  return joinPath(folder, sub, file);
}
function withNumberSuffix(path, n) {
  const extIndex = /\.md$/i.test(path) ? path.length - 3 : path.length;
  return `${path.slice(0, extIndex)} (${n})${path.slice(extIndex)}`;
}
async function uniquePath(path, exists, maxAttempts = 1e3) {
  if (!await exists(path)) return path;
  for (let n = 2; n <= maxAttempts; n++) {
    const candidate = withNumberSuffix(path, n);
    if (!await exists(candidate)) return candidate;
  }
  throw new Error(`\u627E\u4E0D\u5230\u53EF\u7528\u7684\u6A94\u540D\uFF1A${path}`);
}
var YAML_PLAIN = /^[A-Za-z][A-Za-z0-9_-]*$/;
var YAML_RESERVED = /^(true|false|yes|no|on|off|y|n|null|nan|inf)$/i;
function yamlScalar(value) {
  if (value === null || value === void 0) return "null";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "boolean") return String(value);
  const str = String(value);
  if (YAML_PLAIN.test(str) && !YAML_RESERVED.test(str)) return str;
  return JSON.stringify(str);
}
function yamlFlowItem(tag) {
  return /^[\p{L}\p{N}_\-/]+$/u.test(tag) && !YAML_RESERVED.test(tag) ? tag : JSON.stringify(tag);
}
function scanTags(scan) {
  return scan.templateId ? ["localocr", `localocr/${scan.templateId}`] : ["localocr"];
}
function renderFrontmatterLines(scan, templateName, extraTags = []) {
  var _a, _b, _c, _d;
  const lines = [
    `localocr_id: ${JSON.stringify(String(scan.id))}`,
    `created: ${yamlScalar(scan.createdAt)}`,
    `updated: ${yamlScalar(scan.updatedAt)}`,
    `template: ${yamlScalar((_a = scan.templateId) != null ? _a : null)}`,
    `template_name: ${yamlScalar(templateName)}`,
    `source: ${yamlScalar((_b = scan.source) != null ? _b : null)}`
  ];
  const confidence = (_c = scan.classification) == null ? void 0 : _c.confidence;
  if (typeof confidence === "number" && Number.isFinite(confidence)) {
    lines.push(`confidence: ${yamlScalar(confidence)}`);
  }
  const provider = (_d = scan.classification) == null ? void 0 : _d.provider;
  if (typeof provider === "string" && provider) {
    lines.push(`classifier: ${yamlScalar(provider)}`);
  }
  const tags = [];
  for (const tag of [...scanTags(scan), ...extraTags]) {
    if (!tags.includes(tag)) tags.push(tag);
  }
  lines.push(`tags: [${tags.map(yamlFlowItem).join(", ")}]`);
  return lines;
}
function escapeFence(text) {
  return text.replace(/`{3,}/g, (run) => run.split("").join("\u200B"));
}
function neutralizeMarkers(text) {
  return text.split(MARKER_START).join("<!-- localocr\u200B:start -->").split(MARKER_END).join("<!-- localocr\u200B:end -->");
}
function renderBlock(scan, includeText) {
  const lines = [`# ${deriveTitle(scan)}`, "", "## \u7D50\u69CB\u5316\u8CC7\u6599", ""];
  if (scan.data === null || scan.data === void 0) {
    lines.push("_\uFF08\u7121\u7D50\u69CB\u5316\u8CC7\u6599\uFF09_");
  } else {
    lines.push("```json", JSON.stringify(scan.data, null, 2), "```");
  }
  const text = typeof scan.text === "string" ? scan.text.replace(/\r\n?/g, "\n").replace(/\s+$/, "") : "";
  if (includeText && text.trim()) {
    lines.push("", "## \u8FA8\u8B58\u6587\u5B57", "", "```text", escapeFence(text), "```");
  }
  return [MARKER_START, "", neutralizeMarkers(lines.join("\n")), "", MARKER_END].join("\n");
}
function assemble(frontmatterLines, body) {
  return `---
${frontmatterLines.join("\n")}
---
${body}`;
}
function renderNote(scan, opts) {
  return assemble(renderFrontmatterLines(scan, opts.templateName), `${renderBlock(scan, opts.includeText)}
`);
}
function splitFrontmatter(text) {
  const normalized = text.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
  if (!normalized.startsWith("---\n")) return { frontmatter: null, body: normalized };
  const lines = normalized.split("\n");
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trimEnd();
    if (line === "---" || line === "...") {
      return { frontmatter: lines.slice(1, i), body: lines.slice(i + 1).join("\n") };
    }
  }
  return { frontmatter: null, body: normalized };
}
var TOP_LEVEL_KEY = /^("(?:[^"\\]|\\.)*"|'[^']*'|[^\s#\-'"][^:]*?)\s*:(?:\s|$)/;
function unquote(value) {
  const v = value.trim();
  if (v.length >= 2 && (v.startsWith('"') && v.endsWith('"') || v.startsWith("'") && v.endsWith("'"))) {
    if (v.startsWith('"')) {
      try {
        return JSON.parse(v);
      } catch (e) {
        return v.slice(1, -1);
      }
    }
    return v.slice(1, -1).replace(/''/g, "'");
  }
  return v;
}
function parseFrontmatterBlocks(lines) {
  const blocks = [];
  for (const line of lines) {
    const match = TOP_LEVEL_KEY.exec(line);
    if (match) {
      blocks.push({ key: unquote(match[1]), lines: [line] });
    } else if (blocks.length > 0) {
      blocks[blocks.length - 1].lines.push(line);
    } else {
      blocks.push({ key: null, lines: [line] });
    }
  }
  return blocks;
}
function parseTagsBlock(lines) {
  var _a, _b;
  const first = (_a = lines[0]) != null ? _a : "";
  const rest = first.slice(first.indexOf(":") + 1).trim();
  let raw = [];
  if (rest.startsWith("[")) {
    const joined = [rest, ...lines.slice(1).map((l) => l.trim())].join(" ");
    const inner = joined.slice(1, joined.lastIndexOf("]") > 0 ? joined.lastIndexOf("]") : void 0);
    raw = inner.split(",");
  } else if (rest === "" || rest.startsWith("#")) {
    for (const line of lines.slice(1)) {
      const m = (_b = /^\s*-\s+(.*)$/.exec(line)) != null ? _b : /^\s*-$/.exec(line);
      if (m && m[1] !== void 0) raw.push(m[1].replace(/\s+#.*$/, ""));
    }
  } else {
    raw = rest.split(",");
  }
  return raw.map((tag) => unquote(tag).replace(/^#/, "").trim()).filter((tag) => tag.length > 0);
}
function isOwnTag(tag) {
  return tag === "localocr" || tag.startsWith("localocr/");
}
function mergeNote(existing, scan, opts) {
  const { frontmatter, body } = splitFrontmatter(existing);
  const managed = new Set(MANAGED_KEYS);
  const userBlocks = [];
  const extraTags = [];
  if (frontmatter) {
    for (const block2 of parseFrontmatterBlocks(frontmatter)) {
      if (block2.key === "tags") {
        for (const tag of parseTagsBlock(block2.lines)) {
          if (!isOwnTag(tag) && !extraTags.includes(tag)) extraTags.push(tag);
        }
      } else if (block2.key === null || !managed.has(block2.key)) {
        userBlocks.push(...block2.lines);
      }
    }
  }
  const frontmatterLines = [...renderFrontmatterLines(scan, opts.templateName, extraTags), ...userBlocks];
  const block = renderBlock(scan, opts.includeText);
  const start = body.indexOf(MARKER_START);
  const end = start >= 0 ? body.indexOf(MARKER_END, start + MARKER_START.length) : -1;
  let newBody;
  if (start >= 0 && end >= 0) {
    newBody = body.slice(0, start) + block + body.slice(end + MARKER_END.length);
  } else {
    const rest = body.replace(/^\n+/, "");
    newBody = rest.trim() ? `${block}

${rest}` : `${block}
`;
  }
  return assemble(frontmatterLines, newBody);
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  serverUrl: "",
  apiKey: "",
  folder: "LocalOCR",
  subfolderPerTemplate: true,
  autoSyncMinutes: 15,
  includeText: true
};
var LocalOcrSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const settings = this.plugin.settings;
    new import_obsidian.Setting(containerEl).setName("\u9023\u7DDA").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u4F3A\u670D\u5668\u7DB2\u5740").setDesc("LocalOCR \u4F3A\u670D\u5668\u7684\u7DB2\u5740\uFF0C\u4F8B\u5982 https://xxx.up.railway.app\uFF08\u7D50\u5C3E\u4E0D\u9700\u8981\u659C\u7DDA\uFF09\u3002").addText(
      (text) => text.setPlaceholder("https://xxx.up.railway.app").setValue(settings.serverUrl).onChange(async (value) => {
        settings.serverUrl = value.trim().replace(/\/+$/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API \u91D1\u9470").setDesc("\u4F3A\u670D\u5668\u74B0\u5883\u8B8A\u6578 API_KEYS \u4E2D\u7684\u5176\u4E2D\u4E00\u628A\u91D1\u9470\u3002\u91D1\u9470\u6703\u5132\u5B58\u5728\u6B64\u4FDD\u96AA\u5EAB\u7684\u63D2\u4EF6\u8CC7\u6599\u4E2D\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.autocomplete = "off";
      text.setPlaceholder("API \u91D1\u9470").setValue(settings.apiKey).onChange(async (value) => {
        settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u6E2C\u8A66\u9023\u7DDA").setDesc("\u6AA2\u67E5\u4F3A\u670D\u5668 /health\uFF0C\u4E26\u4EE5 API \u91D1\u9470\u8B80\u53D6\u6A23\u677F\u6E05\u55AE\u3002").addButton(
      (button) => button.setButtonText("\u6E2C\u8A66\u9023\u7DDA").onClick(async () => {
        button.setDisabled(true);
        try {
          await this.plugin.testConnection();
        } finally {
          button.setDisabled(false);
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7B46\u8A18").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u76EE\u6A19\u8CC7\u6599\u593E").setDesc("\u540C\u6B65\u7684\u7B46\u8A18\u6703\u653E\u5728\u9019\u500B\u8CC7\u6599\u593E\uFF08\u76F8\u5C0D\u65BC\u4FDD\u96AA\u5EAB\u6839\u76EE\u9304\uFF09\u3002").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.folder).setValue(settings.folder).onChange(async (value) => {
        settings.folder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u4F9D\u6A23\u677F\u5EFA\u7ACB\u5B50\u8CC7\u6599\u593E").setDesc("\u958B\u555F\u6642\uFF0C\u7B46\u8A18\u6703\u4F9D\u6A23\u677F\u540D\u7A31\u5206\u5230\u5B50\u8CC7\u6599\u593E\uFF08\u6C92\u6709\u6A23\u677F\u7684\u653E\u5728\u300C\u672A\u5206\u985E\u300D\uFF09\u3002").addToggle(
      (toggle) => toggle.setValue(settings.subfolderPerTemplate).onChange(async (value) => {
        settings.subfolderPerTemplate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5305\u542B\u8FA8\u8B58\u6587\u5B57").setDesc("\u5728\u7B46\u8A18\u4E2D\u52A0\u5165\u300C\u8FA8\u8B58\u6587\u5B57\u300D\u6BB5\u843D\uFF08OCR \u5168\u6587\uFF09\u3002").addToggle(
      (toggle) => toggle.setValue(settings.includeText).onChange(async (value) => {
        settings.includeText = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u540C\u6B65").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52D5\u540C\u6B65\u9593\u9694\uFF08\u5206\u9418\uFF09").setDesc("\u6BCF\u9694\u5E7E\u5206\u9418\u81EA\u52D5\u540C\u6B65\u4E00\u6B21\uFF1B\u8A2D\u70BA 0 \u8868\u793A\u95DC\u9589\u81EA\u52D5\u540C\u6B65\u3002").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.setPlaceholder(String(DEFAULT_SETTINGS.autoSyncMinutes)).setValue(String(settings.autoSyncMinutes)).onChange(async (value) => {
        const minutes = Number.parseInt(value, 10);
        if (!Number.isFinite(minutes) || minutes < 0) return;
        settings.autoSyncMinutes = minutes;
        await this.plugin.saveSettings();
        this.plugin.scheduleAutoSync();
      });
    });
    const progress = this.plugin.progressDescription();
    new import_obsidian.Setting(containerEl).setName("\u91CD\u8A2D\u540C\u6B65\u9032\u5EA6").setDesc(
      `\u4E0B\u6B21\u540C\u6B65\u6642\u91CD\u65B0\u4E0B\u8F09\u5168\u90E8\u6383\u63CF\uFF1B\u5DF2\u5B58\u5728\u7684\u7B46\u8A18\u6703\u539F\u5730\u66F4\u65B0\uFF0C\u4E0D\u6703\u91CD\u8907\u5EFA\u7ACB\u3002${progress ? `\u76EE\u524D\u9032\u5EA6\uFF1A${progress}` : ""}`
    ).addButton(
      (button) => button.setButtonText("\u91CD\u8A2D\u540C\u6B65\u9032\u5EA6").setWarning().onClick(async () => {
        await this.plugin.resetProgress();
        this.display();
      })
    );
  }
};
function describeProgress(lastSeenUpdatedAt) {
  return lastSeenUpdatedAt ? `\u5DF2\u540C\u6B65\u5230 ${formatDateTime(lastSeenUpdatedAt)} \u66F4\u65B0\u7684\u6383\u63CF\u3002` : "";
}

// src/sync-core.ts
var PAGE_SIZE = 100;
var EPOCH = "1970-01-01T00:00:00.000Z";
var REQUEST_TIMEOUT_MS = 6e4;
var ApiError = class extends Error {
  constructor(message, status, code) {
    super(message);
    this.status = status;
    this.code = code;
    this.name = "ApiError";
  }
  get isAuthError() {
    return this.status === 401 || this.status === 403;
  }
};
function normalizeServerUrl(url) {
  let value = url.trim().replace(/\/+$/, "");
  if (value && !/^[a-z][a-z0-9+.-]*:\/\//i.test(value)) value = `https://${value}`;
  return value;
}
function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(
      () => reject(new ApiError(`\u9023\u7DDA\u903E\u6642\uFF08${Math.round(ms / 1e3)} \u79D2\uFF09`, 0, "timeout")),
      ms
    );
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (error) => {
        clearTimeout(timer);
        reject(error);
      }
    );
  });
}
function statusMessage(status, serverMessage) {
  const detail = serverMessage ? `\uFF1A${serverMessage}` : "";
  if (status === 401) return `API \u91D1\u9470\u7121\u6548\u6216\u672A\u63D0\u4F9B\uFF08401\uFF09${detail}`;
  if (status === 403) return `API \u91D1\u9470\u6C92\u6709\u6B0A\u9650\uFF08403\uFF09${detail}`;
  if (status === 404) return `\u627E\u4E0D\u5230\u7AEF\u9EDE\uFF0C\u8ACB\u78BA\u8A8D\u4F3A\u670D\u5668\u7DB2\u5740\uFF08404\uFF09${detail}`;
  if (status === 429) return `\u8ACB\u6C42\u904E\u65BC\u983B\u7E41\uFF0C\u8ACB\u7A0D\u5F8C\u518D\u8A66\uFF08429\uFF09${detail}`;
  if (status >= 500) return `\u4F3A\u670D\u5668\u932F\u8AA4\uFF08${status}\uFF09${detail}`;
  return `\u8ACB\u6C42\u5931\u6557\uFF08${status}\uFF09${detail}`;
}
var LocalOcrClient = class {
  constructor(baseUrl, apiKey, http, timeoutMs = REQUEST_TIMEOUT_MS) {
    this.apiKey = apiKey;
    this.http = http;
    this.timeoutMs = timeoutMs;
    this.baseUrl = normalizeServerUrl(baseUrl);
  }
  async getJson(path, authenticated) {
    if (!this.baseUrl) throw new ApiError("\u5C1A\u672A\u8A2D\u5B9A\u4F3A\u670D\u5668\u7DB2\u5740", 0, "config");
    if (authenticated && !this.apiKey) throw new ApiError("\u5C1A\u672A\u8A2D\u5B9A API \u91D1\u9470", 0, "config");
    const headers = { Accept: "application/json" };
    if (authenticated) headers.Authorization = `Bearer ${this.apiKey}`;
    let response;
    try {
      response = await withTimeout(this.http({ url: this.baseUrl + path, method: "GET", headers }), this.timeoutMs);
    } catch (error) {
      if (error instanceof ApiError) throw error;
      const reason = error instanceof Error ? error.message : String(error);
      throw new ApiError(`\u7121\u6CD5\u9023\u7DDA\u5230\u4F3A\u670D\u5668\uFF1A${reason}`, 0, "network");
    }
    let body = void 0;
    if (response.text) {
      try {
        body = JSON.parse(response.text);
      } catch (e) {
        body = void 0;
      }
    }
    if (response.status < 200 || response.status >= 300) {
      const err = body == null ? void 0 : body.error;
      const code = typeof (err == null ? void 0 : err.code) === "string" ? err.code : void 0;
      const message = typeof (err == null ? void 0 : err.message) === "string" ? err.message : void 0;
      throw new ApiError(statusMessage(response.status, message), response.status, code);
    }
    if (body === void 0) throw new ApiError("\u4F3A\u670D\u5668\u56DE\u61C9\u4E0D\u662F\u6709\u6548\u7684 JSON", response.status, "bad_response");
    return body;
  }
  async health() {
    const body = await this.getJson("/health", false);
    if (!body || typeof body !== "object" || typeof body.status !== "string") {
      throw new ApiError("\u4F3A\u670D\u5668 /health \u56DE\u61C9\u683C\u5F0F\u4E0D\u6B63\u78BA", 200, "bad_response");
    }
    return body;
  }
  async listTemplates() {
    const body = await this.getJson("/v1/templates", true);
    if (!body || !Array.isArray(body.items)) {
      throw new ApiError("\u4F3A\u670D\u5668 /v1/templates \u56DE\u61C9\u683C\u5F0F\u4E0D\u6B63\u78BA", 200, "bad_response");
    }
    return body.items.filter(
      (t) => !!t && typeof t.id === "string" && typeof t.name === "string"
    );
  }
  async listScans(query) {
    const params = [`limit=${encodeURIComponent(String(query.limit))}`];
    if (query.updatedAfter) params.push(`updatedAfter=${encodeURIComponent(query.updatedAfter)}`);
    if (query.cursor) params.push(`cursor=${encodeURIComponent(query.cursor)}`);
    const body = await this.getJson(`/v1/scans?${params.join("&")}`, true);
    if (!body || !Array.isArray(body.items)) {
      throw new ApiError("\u4F3A\u670D\u5668 /v1/scans \u56DE\u61C9\u683C\u5F0F\u4E0D\u6B63\u78BA", 200, "bad_response");
    }
    const nextCursor = typeof body.nextCursor === "string" && body.nextCursor ? body.nextCursor : null;
    return { items: body.items, nextCursor };
  }
};
function templateNameMap(templates) {
  const map = /* @__PURE__ */ new Map();
  for (const t of templates) map.set(t.id, t.name);
  return map;
}
function describeError(error) {
  if (error instanceof Error) return error.message || error.name;
  return String(error);
}
function initialCursorState() {
  return { cursor: null, updatedAfter: null, lastSeenUpdatedAt: null };
}
function nextScanQuery(state, limit = PAGE_SIZE) {
  var _a;
  const query = { limit, updatedAfter: (_a = state.updatedAfter) != null ? _a : EPOCH };
  if (state.cursor) query.cursor = state.cursor;
  return query;
}
function timeOf(iso) {
  if (typeof iso !== "string") return Number.NaN;
  return new Date(iso).getTime();
}
function lastUpdatedAt(items) {
  var _a;
  for (let i = items.length - 1; i >= 0; i--) {
    const value = (_a = items[i]) == null ? void 0 : _a.updatedAt;
    if (typeof value === "string" && !Number.isNaN(timeOf(value))) return value;
  }
  return null;
}
function laterOf(a, b) {
  if (!a) return b;
  if (!b) return a;
  return timeOf(b) >= timeOf(a) ? b : a;
}
function advanceCursor(state, page) {
  const lastSeen = laterOf(state.lastSeenUpdatedAt, lastUpdatedAt(page.items));
  if (page.nextCursor) {
    const done = page.items.length === 0 || page.nextCursor === state.cursor;
    return {
      state: { cursor: page.nextCursor, updatedAfter: state.updatedAfter, lastSeenUpdatedAt: lastSeen },
      done
    };
  }
  return {
    state: { cursor: null, updatedAfter: lastSeen != null ? lastSeen : state.updatedAfter, lastSeenUpdatedAt: lastSeen },
    done: true
  };
}
var SyncAbortedError = class extends Error {
  constructor(reason, result) {
    super(describeError(reason));
    this.reason = reason;
    this.result = result;
    this.name = "SyncAbortedError";
  }
};
function isValidScan(item) {
  const scan = item;
  return !!scan && typeof scan === "object" && typeof scan.id === "string" && scan.id.length > 0 && typeof scan.updatedAt === "string";
}
async function runSync(deps) {
  var _a, _b, _c, _d, _e;
  const result = { created: 0, updated: 0, unchanged: 0, failed: 0, pages: 0, errors: [] };
  const pageSize = (_a = deps.pageSize) != null ? _a : PAGE_SIZE;
  const maxPages = (_b = deps.maxPages) != null ? _b : 1e4;
  let state = { ...deps.state };
  try {
    const templates = templateNameMap(await deps.client.listTemplates());
    for (; ; ) {
      if ((_c = deps.isCancelled) == null ? void 0 : _c.call(deps)) break;
      const page = await deps.client.listScans(nextScanQuery(state, pageSize));
      result.pages++;
      for (const item of page.items) {
        if ((_d = deps.isCancelled) == null ? void 0 : _d.call(deps)) return result;
        if (!isValidScan(item)) {
          result.failed++;
          if (result.errors.length < 5) result.errors.push("\u4F3A\u670D\u5668\u56DE\u50B3\u4E86\u683C\u5F0F\u4E0D\u6B63\u78BA\u7684\u6383\u63CF\u7D00\u9304");
          continue;
        }
        try {
          const outcome = await deps.writeScan(item, templates);
          result[outcome]++;
        } catch (error) {
          result.failed++;
          if (result.errors.length < 5) result.errors.push(`${item.id}\uFF1A${describeError(error)}`);
        }
      }
      const advance = advanceCursor(state, page);
      state = advance.state;
      await deps.saveState(state);
      (_e = deps.onProgress) == null ? void 0 : _e.call(deps, result);
      if (advance.done || result.pages >= maxPages) break;
    }
  } catch (error) {
    throw new SyncAbortedError(error, result);
  }
  return result;
}
function summarize(result) {
  const parts = [`\u65B0\u589E ${result.created} \u7B46`, `\u66F4\u65B0 ${result.updated} \u7B46`];
  if (result.unchanged) parts.push(`\u672A\u8B8A\u66F4 ${result.unchanged} \u7B46`);
  if (result.failed) parts.push(`\u5931\u6557 ${result.failed} \u7B46`);
  return parts.join("\u3001");
}

// src/main.ts
var LOG_PREFIX = "[LocalOCR Sync]";
var STARTUP_SYNC_DELAY_MS = 5e3;
var obsidianHttp = async (request) => {
  const response = await (0, import_obsidian2.requestUrl)({
    url: request.url,
    method: request.method,
    headers: request.headers,
    throw: false
  });
  let text = "";
  try {
    text = response.text;
  } catch (e) {
    text = "";
  }
  return { status: response.status, text };
};
var LocalOcrSyncPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.syncState = initialCursorState();
    this.meta = { lastSyncAt: null, lastSyncCount: 0 };
    this.paths = {};
    this.syncing = false;
    this.unloaded = false;
    this.lastSyncFailed = false;
    this.autoSyncTimer = null;
    this.startupTimer = null;
    this.statusBarEl = null;
    /** localocr_id → file, built lazily from the metadata cache once per sync. */
    this.frontmatterIndex = null;
    this.requestSave = (0, import_obsidian2.debounce)(() => void this.savePluginData(), 1e3, true);
  }
  async onload() {
    await this.loadPluginData();
    this.addSettingTab(new LocalOcrSettingTab(this.app, this));
    this.statusBarEl = this.addStatusBarItem();
    this.statusBarEl.addClass("mod-clickable");
    this.registerDomEvent(this.statusBarEl, "click", () => void this.sync({ manual: true }));
    this.renderIdleStatus();
    this.addRibbonIcon("scan-text", "\u7ACB\u5373\u540C\u6B65 LocalOCR", () => void this.sync({ manual: true }));
    this.addCommand({
      id: "sync-now",
      name: "\u7ACB\u5373\u540C\u6B65 LocalOCR",
      callback: () => void this.sync({ manual: true })
    });
    this.addCommand({
      id: "resync-all",
      name: "\u91CD\u65B0\u540C\u6B65\u5168\u90E8\uFF08\u91CD\u8A2D\u9032\u5EA6\uFF09",
      callback: async () => {
        if (await this.resetProgress(false)) await this.sync({ manual: true });
      }
    });
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => this.onFileRenamed(file, oldPath)));
    this.registerEvent(this.app.vault.on("delete", (file) => this.onFileDeleted(file)));
    this.app.workspace.onLayoutReady(() => {
      this.scheduleAutoSync();
      if (this.settings.autoSyncMinutes > 0 && this.isConfigured()) {
        this.startupTimer = window.setTimeout(() => {
          this.startupTimer = null;
          void this.sync({ manual: false });
        }, STARTUP_SYNC_DELAY_MS);
      }
    });
  }
  onunload() {
    this.unloaded = true;
    this.requestSave.run();
    if (this.startupTimer !== null) window.clearTimeout(this.startupTimer);
    if (this.autoSyncTimer !== null) window.clearInterval(this.autoSyncTimer);
  }
  // -------------------------------------------------------------------------
  // Persistence
  async loadPluginData() {
    var _a, _b, _c, _d, _e;
    const raw = (_a = await this.loadData()) != null ? _a : {};
    this.settings = { ...DEFAULT_SETTINGS, ...(_b = raw.settings) != null ? _b : {} };
    if (typeof this.settings.autoSyncMinutes !== "number" || !(this.settings.autoSyncMinutes >= 0)) {
      this.settings.autoSyncMinutes = DEFAULT_SETTINGS.autoSyncMinutes;
    }
    this.syncState = { ...initialCursorState(), ...(_c = raw.sync) != null ? _c : {} };
    this.meta = { lastSyncAt: null, lastSyncCount: 0, ...(_d = raw.meta) != null ? _d : {} };
    this.paths = { ...(_e = raw.paths) != null ? _e : {} };
  }
  async savePluginData() {
    const data = {
      settings: this.settings,
      sync: this.syncState,
      meta: this.meta,
      paths: this.paths
    };
    await this.saveData(data);
  }
  async saveSettings() {
    await this.savePluginData();
  }
  // -------------------------------------------------------------------------
  // Public actions (commands, settings tab)
  isConfigured() {
    return normalizeServerUrl(this.settings.serverUrl).length > 0 && this.settings.apiKey.length > 0;
  }
  createClient() {
    return new LocalOcrClient(this.settings.serverUrl, this.settings.apiKey, obsidianHttp);
  }
  scheduleAutoSync() {
    if (this.autoSyncTimer !== null) {
      window.clearInterval(this.autoSyncTimer);
      this.autoSyncTimer = null;
    }
    const minutes = this.settings.autoSyncMinutes;
    if (!(minutes > 0)) return;
    this.autoSyncTimer = this.registerInterval(
      window.setInterval(() => void this.sync({ manual: false }), minutes * 6e4)
    );
  }
  progressDescription() {
    return describeProgress(this.syncState.lastSeenUpdatedAt);
  }
  /** Clears the cursor so the next sync re-downloads everything. Notes are updated in place. */
  async resetProgress(notify = true) {
    if (this.syncing) {
      new import_obsidian2.Notice("LocalOCR\uFF1A\u540C\u6B65\u9032\u884C\u4E2D\uFF0C\u8ACB\u7A0D\u5F8C\u518D\u91CD\u8A2D\u9032\u5EA6");
      return false;
    }
    this.syncState = initialCursorState();
    await this.savePluginData();
    if (notify) new import_obsidian2.Notice("LocalOCR\uFF1A\u5DF2\u91CD\u8A2D\u540C\u6B65\u9032\u5EA6\uFF0C\u4E0B\u6B21\u540C\u6B65\u6703\u91CD\u65B0\u4E0B\u8F09\u5168\u90E8\u6383\u63CF");
    return true;
  }
  async testConnection() {
    var _a;
    if (!normalizeServerUrl(this.settings.serverUrl)) {
      new import_obsidian2.Notice("LocalOCR\uFF1A\u8ACB\u5148\u586B\u5165\u4F3A\u670D\u5668\u7DB2\u5740");
      return;
    }
    const client = this.createClient();
    let version = "";
    let database = "";
    try {
      const health = await client.health();
      version = health.version ? `v${health.version}` : "";
      database = (_a = health.database) != null ? _a : "";
    } catch (error) {
      new import_obsidian2.Notice(`LocalOCR\uFF1A\u7121\u6CD5\u9023\u7DDA\u5230\u4F3A\u670D\u5668\uFF08/health\uFF09
${describeError(error)}`, 1e4);
      return;
    }
    const serverInfo = [version, database ? `\u8CC7\u6599\u5EAB ${database}` : ""].filter(Boolean).join("\uFF0C");
    if (!this.settings.apiKey) {
      new import_obsidian2.Notice(`LocalOCR\uFF1A\u4F3A\u670D\u5668\u53EF\u9023\u7DDA\uFF08${serverInfo || "\u6B63\u5E38"}\uFF09\uFF0C\u4F46\u5C1A\u672A\u586B\u5165 API \u91D1\u9470`, 8e3);
      return;
    }
    try {
      const templates = await client.listTemplates();
      new import_obsidian2.Notice(
        `LocalOCR\uFF1A\u9023\u7DDA\u6210\u529F\uFF01\u4F3A\u670D\u5668 ${serverInfo || "\u6B63\u5E38"}\uFF0CAPI \u91D1\u9470\u6709\u6548\uFF0C\u5171 ${templates.length} \u500B\u6A23\u677F\u3002`,
        8e3
      );
    } catch (error) {
      new import_obsidian2.Notice(`LocalOCR\uFF1A\u4F3A\u670D\u5668\u53EF\u9023\u7DDA\uFF0C\u4F46\u8B80\u53D6\u6A23\u677F\u5931\u6557
${describeError(error)}`, 1e4);
    }
  }
  async sync(opts) {
    if (this.syncing) {
      if (opts.manual) new import_obsidian2.Notice("LocalOCR\uFF1A\u540C\u6B65\u9032\u884C\u4E2D\uFF0C\u8ACB\u7A0D\u5019");
      return;
    }
    if (!this.isConfigured()) {
      if (opts.manual) new import_obsidian2.Notice("LocalOCR\uFF1A\u8ACB\u5148\u5728\u8A2D\u5B9A\u4E2D\u586B\u5165\u4F3A\u670D\u5668\u7DB2\u5740\u8207 API \u91D1\u9470");
      return;
    }
    this.syncing = true;
    this.frontmatterIndex = null;
    this.setStatus("LocalOCR\uFF1A\u540C\u6B65\u4E2D\u2026");
    try {
      const result = await runSync({
        client: this.createClient(),
        state: this.syncState,
        writeScan: (scan, templates) => this.writeScan(scan, templates),
        saveState: async (state) => {
          this.syncState = state;
          await this.savePluginData();
        },
        isCancelled: () => this.unloaded,
        onProgress: (r) => this.setStatus(`LocalOCR\uFF1A\u540C\u6B65\u4E2D\u2026\uFF08${r.created + r.updated + r.unchanged} \u7B46\uFF09`)
      });
      if (this.unloaded) return;
      this.meta = { lastSyncAt: (/* @__PURE__ */ new Date()).toISOString(), lastSyncCount: result.created + result.updated };
      await this.savePluginData();
      this.lastSyncFailed = false;
      this.renderIdleStatus();
      if (opts.manual) new import_obsidian2.Notice(`LocalOCR \u540C\u6B65\u5B8C\u6210\uFF1A${summarize(result)}`);
      if (result.failed > 0) {
        console.warn(LOG_PREFIX, "\u90E8\u5206\u6383\u63CF\u7121\u6CD5\u5BEB\u5165\uFF1A", result.errors);
        new import_obsidian2.Notice(`LocalOCR\uFF1A${result.failed} \u7B46\u6383\u63CF\u7121\u6CD5\u5BEB\u5165
${result.errors.join("\n")}`, 15e3);
      }
    } catch (error) {
      const message = describeError(error);
      this.setStatus("LocalOCR\uFF1A\u540C\u6B65\u5931\u6557", message);
      if (opts.manual || !this.lastSyncFailed) {
        const partial = error instanceof SyncAbortedError ? error.result : null;
        const done = partial ? partial.created + partial.updated + partial.unchanged : 0;
        const extra = done > 0 ? `
\uFF08\u5DF2\u8655\u7406 ${done} \u7B46\uFF0C\u4E0B\u6B21\u6703\u5F9E\u4E2D\u65B7\u8655\u7E7C\u7E8C\uFF09` : "";
        new import_obsidian2.Notice(`LocalOCR \u540C\u6B65\u5931\u6557\uFF1A${message}${extra}`, 1e4);
      }
      this.lastSyncFailed = true;
      console.error(LOG_PREFIX, "\u540C\u6B65\u5931\u6557\uFF1A", message);
    } finally {
      this.syncing = false;
      this.frontmatterIndex = null;
    }
  }
  // -------------------------------------------------------------------------
  // Notes
  async writeScan(scan, templates) {
    const templateName = resolveTemplateName(scan.templateId, templates);
    const opts = { templateName, includeText: this.settings.includeText };
    const existing = this.findNoteFor(scan.id);
    if (existing) {
      this.paths[scan.id] = existing.path;
      const current = await this.app.vault.read(existing);
      if (mergeNote(current, scan, opts) === current) return "unchanged";
      await this.app.vault.process(existing, (data) => mergeNote(data, scan, opts));
      return "updated";
    }
    const desired = (0, import_obsidian2.normalizePath)(
      buildNotePath(scan, {
        folder: this.settings.folder,
        subfolderPerTemplate: this.settings.subfolderPerTemplate,
        templateName
      })
    );
    const slash = desired.lastIndexOf("/");
    if (slash > 0) await this.ensureFolder(desired.slice(0, slash));
    const path = await uniquePath(desired, (candidate) => this.pathExists(candidate));
    const file = await this.app.vault.create(path, renderNote(scan, opts));
    this.paths[scan.id] = file.path;
    return "created";
  }
  /** The note previously written for this scan, if it still exists. */
  findNoteFor(scanId) {
    const mapped = this.paths[scanId];
    if (mapped) {
      const file = this.app.vault.getAbstractFileByPath(mapped);
      if (file instanceof import_obsidian2.TFile) return file;
    }
    const indexed = this.getFrontmatterIndex().get(scanId);
    if (indexed && this.app.vault.getAbstractFileByPath(indexed.path) === indexed) return indexed;
    return null;
  }
  getFrontmatterIndex() {
    var _a, _b;
    if (!this.frontmatterIndex) {
      const index = /* @__PURE__ */ new Map();
      for (const file of this.app.vault.getMarkdownFiles()) {
        const id = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.localocr_id;
        if (typeof id === "string" && id && !index.has(id)) index.set(id, file);
      }
      this.frontmatterIndex = index;
    }
    return this.frontmatterIndex;
  }
  async pathExists(path) {
    if (this.app.vault.getAbstractFileByPath(path)) return true;
    return this.app.vault.adapter.exists(path);
  }
  async ensureFolder(folder) {
    let current = "";
    for (const part of folder.split("/")) {
      current = current ? `${current}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing instanceof import_obsidian2.TFolder) continue;
      if (existing) throw new Error(`\u300C${current}\u300D\u5DF2\u5B58\u5728\u4E14\u4E0D\u662F\u8CC7\u6599\u593E`);
      try {
        await this.app.vault.createFolder(current);
      } catch (error) {
        if (!(this.app.vault.getAbstractFileByPath(current) instanceof import_obsidian2.TFolder)) throw error;
      }
    }
  }
  onFileRenamed(file, oldPath) {
    let changed = false;
    const prefix = `${oldPath}/`;
    for (const [id, path] of Object.entries(this.paths)) {
      if (path === oldPath) {
        this.paths[id] = file.path;
        changed = true;
      } else if (file instanceof import_obsidian2.TFolder && path.startsWith(prefix)) {
        this.paths[id] = `${file.path}/${path.slice(prefix.length)}`;
        changed = true;
      }
    }
    if (changed) this.requestSave();
  }
  onFileDeleted(file) {
    let changed = false;
    const prefix = `${file.path}/`;
    for (const [id, path] of Object.entries(this.paths)) {
      if (path === file.path || path.startsWith(prefix)) {
        delete this.paths[id];
        changed = true;
      }
    }
    if (changed) this.requestSave();
  }
  // -------------------------------------------------------------------------
  // Status bar
  setStatus(text, tooltip) {
    if (!this.statusBarEl) return;
    this.statusBarEl.setText(text);
    this.statusBarEl.setAttr("aria-label", tooltip != null ? tooltip : "\u9EDE\u4E00\u4E0B\u7ACB\u5373\u540C\u6B65 LocalOCR");
    this.statusBarEl.setAttr("data-tooltip-position", "top");
  }
  renderIdleStatus() {
    const { lastSyncAt, lastSyncCount } = this.meta;
    if (lastSyncAt) {
      const date = new Date(lastSyncAt);
      this.setStatus(
        `LocalOCR\uFF1A${formatClock(date)} \u5DF2\u540C\u6B65 ${lastSyncCount} \u7B46`,
        `\u4E0A\u6B21\u540C\u6B65\uFF1A${formatDateTime(lastSyncAt)}\uFF08\u9EDE\u4E00\u4E0B\u7ACB\u5373\u540C\u6B65\uFF09`
      );
    } else {
      this.setStatus("LocalOCR\uFF1A\u5C1A\u672A\u540C\u6B65");
    }
  }
};
